DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS community;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS vote;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  user_pwd TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  karma INTEGER NOT NULL
);

CREATE TABLE community (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  community_name TEXT UNIQUE NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  author_id INTEGER NOT NULL,
  community_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (community_id) REFERENCES community (id)
);

CREATE TABLE vote (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  upvote INTEGER NOT NULL,
  downvote INTEGER NOT NULL
);

COMMIT;
