test_name: Make sure valid inputs are handled correctly
stages:
  - name: Valid signup request (change number if running test more than once or delete the db)
    request:
      url: http://localhost:5000/signup
      json:
        username: 'tavern_username_1'
        password: 'tavern_password_1'
        email: 'email_1@tavern.com'
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 201
      body:
        {}
      headers:
        content-type: application/json
  
---
  
test_name: Make sure invalid inputs are handled correctly
stages:
  - name: Send a duplicate username
    request:
      url: http://localhost:5000/signup
      json:
        username: 'tavern_username_1'
        password: 'tavern_password_1'
        email: 'email_2@tavern.com'
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 409
      body:
        error: 'There was an error processing your data'
      headers:
        content-type: application/json

  - name: Send a duplicate email
    request:
      url: http://localhost:5000/signup
      json:
        username: 'tavern_username_2'
        password: 'tavern_password_2'
        email: 'email_1@tavern.com'
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 409
      body:
        error: 'There was an error processing your data'
      headers:
        content-type: application/json

  - name: Use a wrong key (missing data)
    request:
      url: http://localhost:5000/signup
      json:
        username_wrong_key: 'tavern_username_1'
        password: 'tavern_password_1'
        email: 'email_2@tavern.com'
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 409
      body:
        error: 'There was an error reading your data'
      headers:
        content-type: application/json